### ISSUE TITLE
Passing options throws error

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [koenz/angular-datepicker#1]
When you pass option as input to the animated datepicker it throws an error. To fix that `goToDate()` should use a fallback value for the date which is not provided as parameter, see: 

- https://github.com/koenz/angular-datepicker/blob/develop/src/libs/ngx-animating-datepicker/src/components/animatepicker/animatepicker.component.ts#L108

A simple change to the following should be enough I think: 

``` ts
goToDate(date: Date = this.date): void {
	this.currentYearMonth = this.getNextYearMonthArray(date.getFullYear(), date.getMonth());
	this.calendarWidth = 50 / this._numberOfMonths.length;
	this.months = this.getNextMonthArray(this.currentYearMonth, true);
	this.resetStyle();
}
```
 But you had some conditions in, perhaps you had some things in place I did not considered ...

**Comment by koenz** [comment]
This is solved in the new version
