### ISSUE TITLE
Datepicker Jumps back to current date

### ISSUE THREAD

**Issue by 3makkk** [koenz/angular-datepicker#14]
The default Datepicker `<aa-datepicker>` jumps back to the current date when the selected date input changes. 
Seems like to be an issue with the goToDate implementation since its using the current date as default parameter.

**Comment by koenz** [comment]
`aa-datepicker` will be deprecated, it will be merged with the `aa-animatepicker`

**Comment by 3makkk** [comment]
Okay will give it a try with the animated datepicker
