### ISSUE TITLE
is there any way to have an apply button?

### ISSUE THREAD

**Issue by idomiralin** [koenz/angular-datepicker#2]
We need an apply button and by clicking on this button, the calendar should be closed and only the input should be displayed.

**Comment by koenz** [comment]
I was in the process of making it more composable. Will try to finish that over the weekend. 

You would be able to add your button to the top or the bottom of the datepicker, and create your own logic with it. Hopefully that would help

**Comment by idomiralin** [comment]
Hello koenz. Thank you very much for doing this. Can you let me know here please when it is finished?

**Comment by idomiralin** [comment]
Your calendar is really the greatest that I have found on the internet, but without apply and cancel button it would be hard to use.

**Comment by koenz** [comment]
Will let you know when it finished. you would probably have to do something like this:
`
                    <aa-animatepicker
                            [options]="animateOptions"
                            [(selectedDates)]="selectedDatesAnimate">
                            <footer #footer>
                                <button>Apply</button>
                            </footer>
                    </aa-animatepicker>
`

**Comment by koenz** [comment]
I added the option to add a custom header or footer. I will consider adding the not-emit option in the future, but for now I think it can be achieved with the current state. Hopefully it helps.

You can implement it by doing this:
```html
<aa-animatepicker
	[options]="datepickerOptions"
	[(selectedDates)]="dates">
	<header (click)="someLogic()">put your logic here</header>
	<footer (click)="someLogic()">put your logic here</footer>
</aa-animatepicker>
```

Soon I will publish some examples where I implement something similar.

**Comment by idomiralin** [comment]
Hi Koenz,

How is it possible to use header or footer with directive?

I mean if we need an input...

<input  
                    type="text"  
                    value="dates | date" 
                    [options]="datepickerOptions" 
                    [(selectedDates)]="dates" />

Or should the header and footer be used?

**Comment by koenz** [comment]
Hi, No that is not possible for now. Please use the regular component for that. I might think about a solution for that in the future.
