### ISSUE TITLE
wrong number of day when use weekStart.

### ISSUE THREAD

**Issue by topseom** [koenz/angular-datepicker#3]
i'm try to set option weekStart from monday to sunday but number day of months all wrong.
example 
July should start day number 1 and end at 31. 
but when i'm set weekStart to sunday July start 7 and end at 37. 

this my option 
> public datepickerOptions = {
    selectMultiple:true,
    range:false,
    hideRestDays:true,
    disableRestDays:true,
    animationSpeed:0,
    timeoutBeforeClosing:0,
    weekStart:'sunday'
  }

this my element 

>  <aa-animatepicker [numberOfMonths]="2" [options]="datepickerOptions"></aa-animatepicker/>

this my dependentcies

> "ngx-animating-datepicker": "^1.2.0",
"@angular/core": "6.1.10",

**Comment by koenz** [comment]
This is a bug. Will be solved soon

**Comment by topseom** [comment]
Thank you very much. i will wait for you fix this bug. 
this lib is very great to integrate with angular material, but this bug i can't to use in production.

**Comment by koenz** [comment]
This is fixed. You can now choose any starting day you like. Will close the issue
